blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Docs
    url: /#gh-repo-automation
    about: Checkout the documentation
  - name: ğŸš€ Feature Request
    url: /discussions/new?category=ideas
    about: Share ideas for new features
  - name: â“ Ask a Question
    url: /discussions/new?category=q-a
    about: Ask the community for help